[SETTINGS]
# Время ожидания в секундах, если сайт выдал ошибку или дизайн изменился
check_interval_seconds = 14500
fallback_interval_seconds = 14500

[RESUMES]
# Полные ссылки на резюме
resume_main = https://hh.ru/resume/...
# resume_2 = https://hh.ru